## Gather

In [1]:
import pandas as pd
df_1 = pd.read_csv('twitter-archive-enhanced.csv')
df_1.head()

tweet_id  in_reply_to_status_id  in_reply_to_user_id  \
0  892420643555336193                    NaN                  NaN   
1  892177421306343426                    NaN                  NaN   
2  891815181378084864                    NaN                  NaN   
3  891689557279858688                    NaN                  NaN   
4  891327558926688256                    NaN                  NaN   

                   timestamp  \
0  2017-08-01 16:23:56 +0000   
1  2017-08-01 00:17:27 +0000   
2  2017-07-31 00:18:03 +0000   
3  2017-07-30 15:58:51 +0000   
4  2017-07-29 16:00:24 +0000   

                                              source  \
0  <a href="http://twitter.com/download/iphone" r...   
1  <a href="http://twitter.com/download/iphone" r...   
2  <a href="http://twitter.com/download/iphone" r...   
3  <a href="http://twitter.com/download/iphone" r...   
4  <a href="http://twitter.com/download/iphone" r...   

                                                text  retweeted_status_id  \
0  This is Phineas. He's a mystical boy. Only eve...                  NaN   
1  This is Tilly. She's just checking pup on you....                  NaN   
2  This is Archie. He is a rare Norwegian Pouncin...                  NaN   
3  This is Darla. She commenced a snooze mid meal...                  NaN   
4  This is Franklin. He would like you to stop ca...                  NaN   

   retweeted_status_user_id retweeted_status_timestamp  \
0                       NaN                        NaN   
1                       NaN                        NaN   
2                       NaN                        NaN   
3                       NaN                        NaN   
4                       NaN                        NaN   

                                       expanded_urls  rating_numerator  \
0  https://twitter.com/dog_rates/status/892420643...                13   
1  https://twitter.com/dog_rates/status/892177421...                13   
2  https://twitter.com/dog_rates/status/891815181...                12   
3  https://twitter.com/dog_rates/status/891689557...                13   
4  https://twitter.com/dog_rates/status/891327558...                12   

   rating_denominator      name doggo floofer pupper puppo  
0                  10   Phineas  None    None   None  None  
1                  10     Tilly  None    None   None  None  
2                  10    Archie  None    None   None  None  
3                  10     Darla  None    None   None  None  
4                  10  Franklin  None    None   None  None

In [2]:
import tweepy
from tweepy import OAuthHandler
import json
from timeit import default_timer as timer

if False:
    consumer_key = 'HIDDEN'
    consumer_secret = 'HIDDEN'
    access_token = 'HIDDEN'
    access_secret = 'HIDDEN'

    auth = OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_secret)

    api = tweepy.API(auth, wait_on_rate_limit=True)

    tweet_ids = df_1.tweet_id.values
    len(tweet_ids)

    # Query Twitter's API for JSON data for each tweet ID in the Twitter archive
    count = 0
    fails_dict = {}
    start = timer()
    # Save each tweet's returned JSON as a new line in a .txt file
    with open('tweet_json.txt', 'w') as outfile:
        # This loop will likely take 20-30 minutes to run because of Twitter's rate limit
        for tweet_id in tweet_ids:
            count += 1
            print(str(count) + ": " + str(tweet_id))
            try:
                tweet = api.get_status(tweet_id, tweet_mode='extended')
                print("Success")
                json.dump(tweet._json, outfile)
                outfile.write('\n')
            except tweepy.TweepError as e:
                print("Fail")
                fails_dict[tweet_id] = e
                pass
    end = timer()
    print(end - start)
    print(fails_dict)

In [3]:
df_image=pd.read_csv('image-predictions.tsv',sep='\t')

In [4]:
with open('tweet_json.txt', 'r') as file:
    tweet_json = pd.read_json('tweet_json.txt', lines=True)

In [5]:
tweet_json

contributors  coordinates          created_at display_text_range  \
0              NaN          NaN 2017-08-01 16:23:56            [0, 85]   
1              NaN          NaN 2017-08-01 00:17:27           [0, 138]   
2              NaN          NaN 2017-07-31 00:18:03           [0, 121]   
3              NaN          NaN 2017-07-30 15:58:51            [0, 79]   
4              NaN          NaN 2017-07-29 16:00:24           [0, 138]   
5              NaN          NaN 2017-07-29 00:08:17           [0, 138]   
6              NaN          NaN 2017-07-28 16:27:12           [0, 140]   
7              NaN          NaN 2017-07-28 00:22:40           [0, 118]   
8              NaN          NaN 2017-07-27 16:25:51           [0, 122]   
9              NaN          NaN 2017-07-26 15:59:51           [0, 133]   
10             NaN          NaN 2017-07-26 00:31:25           [0, 130]   
11             NaN          NaN 2017-07-25 16:11:53           [0, 107]   
12             NaN          NaN 2017-07-25 01:55:32           [0, 106]   
13             NaN          NaN 2017-07-25 00:10:02            [0, 91]   
14             NaN          NaN 2017-07-24 17:02:04           [0, 118]   
15             NaN          NaN 2017-07-24 00:19:32           [0, 138]   
16             NaN          NaN 2017-07-23 00:22:39            [0, 86]   
17             NaN          NaN 2017-07-22 16:56:37           [0, 128]   
18             NaN          NaN 2017-07-22 00:23:06            [0, 87]   
19             NaN          NaN 2017-07-20 16:49:33           [0, 127]   
20             NaN          NaN 2017-07-19 16:06:48           [0, 127]   
21             NaN          NaN 2017-07-19 03:39:09           [0, 108]   
22             NaN          NaN 2017-07-19 00:47:34            [0, 99]   
23             NaN          NaN 2017-07-18 16:08:03            [0, 88]   
24             NaN          NaN 2017-07-18 00:07:08           [0, 129]   
25             NaN          NaN 2017-07-17 16:17:36           [0, 101]   
26             NaN          NaN 2017-07-16 23:58:41           [0, 121]   
27             NaN          NaN 2017-07-16 20:14:00            [0, 71]   
28             NaN          NaN 2017-07-15 23:25:31           [0, 131]   
29             NaN          NaN 2017-07-15 16:51:35          [27, 105]   
...            ...          ...                 ...                ...   
2324           NaN          NaN 2015-11-17 00:24:19           [0, 140]   
2325           NaN          NaN 2015-11-17 00:06:54           [0, 139]   
2326           NaN          NaN 2015-11-16 23:23:41           [0, 137]   
2327           NaN          NaN 2015-11-16 21:54:18            [0, 81]   
2328           NaN          NaN 2015-11-16 21:10:36           [0, 140]   
2329           NaN          NaN 2015-11-16 20:32:58           [0, 135]   
2330           NaN          NaN 2015-11-16 20:01:42           [0, 112]   
2331           NaN          NaN 2015-11-16 19:31:45           [0, 139]   
2332           NaN          NaN 2015-11-16 16:37:02           [0, 138]   
2333           NaN          NaN 2015-11-16 16:11:11           [0, 136]   
2334           NaN          NaN 2015-11-16 15:14:19            [0, 46]   
2335           NaN          NaN 2015-11-16 14:57:41            [0, 82]   
2336           NaN          NaN 2015-11-16 04:02:55           [0, 134]   
2337           NaN          NaN 2015-11-16 03:55:04           [0, 128]   
2338           NaN          NaN 2015-11-16 03:44:34           [0, 140]   
2339           NaN          NaN 2015-11-16 03:22:39           [0, 132]   
2340           NaN          NaN 2015-11-16 02:38:37           [0, 125]   
2341           NaN          NaN 2015-11-16 01:59:36           [0, 137]   
2342           NaN          NaN 2015-11-16 01:52:02           [0, 137]   
2343           NaN          NaN 2015-11-16 01:22:45           [0, 107]   
2344           NaN          NaN 2015-11-16 01:01:59           [0, 135]   
2345           NaN          NaN 2015-11-16 00:55:59           [0, 124]   
2346      

# Assess

Assess df_1

In [6]:
df_1.head()

tweet_id  in_reply_to_status_id  in_reply_to_user_id  \
0  892420643555336193                    NaN                  NaN   
1  892177421306343426                    NaN                  NaN   
2  891815181378084864                    NaN                  NaN   
3  891689557279858688                    NaN                  NaN   
4  891327558926688256                    NaN                  NaN   

                   timestamp  \
0  2017-08-01 16:23:56 +0000   
1  2017-08-01 00:17:27 +0000   
2  2017-07-31 00:18:03 +0000   
3  2017-07-30 15:58:51 +0000   
4  2017-07-29 16:00:24 +0000   

                                              source  \
0  <a href="http://twitter.com/download/iphone" r...   
1  <a href="http://twitter.com/download/iphone" r...   
2  <a href="http://twitter.com/download/iphone" r...   
3  <a href="http://twitter.com/download/iphone" r...   
4  <a href="http://twitter.com/download/iphone" r...   

                                                text  retweeted_status_id  \
0  This is Phineas. He's a mystical boy. Only eve...                  NaN   
1  This is Tilly. She's just checking pup on you....                  NaN   
2  This is Archie. He is a rare Norwegian Pouncin...                  NaN   
3  This is Darla. She commenced a snooze mid meal...                  NaN   
4  This is Franklin. He would like you to stop ca...                  NaN   

   retweeted_status_user_id retweeted_status_timestamp  \
0                       NaN                        NaN   
1                       NaN                        NaN   
2                       NaN                        NaN   
3                       NaN                        NaN   
4                       NaN                        NaN   

                                       expanded_urls  rating_numerator  \
0  https://twitter.com/dog_rates/status/892420643...                13   
1  https://twitter.com/dog_rates/status/892177421...                13   
2  https://twitter.com/dog_rates/status/891815181...                12   
3  https://twitter.com/dog_rates/status/891689557...                13   
4  https://twitter.com/dog_rates/status/891327558...                12   

   rating_denominator      name doggo floofer pupper puppo  
0                  10   Phineas  None    None   None  None  
1                  10     Tilly  None    None   None  None  
2                  10    Archie  None    None   None  None  
3                  10     Darla  None    None   None  None  
4                  10  Franklin  None    None   None  None

In [7]:
df_1.info()
# tweet id should be object
# retweeted_status_id  should be object
# retweeted_status_user_id should be object
# timestamp should be date time
# retweeted_status_timestamp should be date time
# expanded_urls should contain only the link not html command

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 17 columns):
tweet_id                      2356 non-null int64
in_reply_to_status_id         78 non-null float64
in_reply_to_user_id           78 non-null float64
timestamp                     2356 non-null object
source                        2356 non-null object
text                          2356 non-null object
retweeted_status_id           181 non-null float64
retweeted_status_user_id      181 non-null float64
retweeted_status_timestamp    181 non-null object
expanded_urls                 2297 non-null object
rating_numerator              2356 non-null int64
rating_denominator            2356 non-null int64
name                          2356 non-null object
doggo                         2356 non-null object
floofer                       2356 non-null object
pupper                        2356 non-null object
puppo                         2356 non-null object
dtypes: float64(4), int64(3), ob

In [8]:
list(df_1)

['tweet_id',
 'in_reply_to_status_id',
 'in_reply_to_user_id',
 'timestamp',
 'source',
 'text',
 'retweeted_status_id',
 'retweeted_status_user_id',
 'retweeted_status_timestamp',
 'expanded_urls',
 'rating_numerator',
 'rating_denominator',
 'name',
 'doggo',
 'floofer',
 'pupper',
 'puppo']

In [9]:
df_1.describe()

tweet_id  in_reply_to_status_id  in_reply_to_user_id  \
count  2.356000e+03           7.800000e+01         7.800000e+01   
mean   7.427716e+17           7.455079e+17         2.014171e+16   
std    6.856705e+16           7.582492e+16         1.252797e+17   
min    6.660209e+17           6.658147e+17         1.185634e+07   
25%    6.783989e+17           6.757419e+17         3.086374e+08   
50%    7.196279e+17           7.038708e+17         4.196984e+09   
75%    7.993373e+17           8.257804e+17         4.196984e+09   
max    8.924206e+17           8.862664e+17         8.405479e+17   

       retweeted_status_id  retweeted_status_user_id  rating_numerator  \
count         1.810000e+02              1.810000e+02       2356.000000   
mean          7.720400e+17              1.241698e+16         13.126486   
std           6.236928e+16              9.599254e+16         45.876648   
min           6.661041e+17              7.832140e+05          0.000000   
25%           7.186315e+17              4.196984e+09         10.000000   
50%           7.804657e+17              4.196984e+09         11.000000   
75%           8.203146e+17              4.196984e+09         12.000000   
max           8.874740e+17              7.874618e+17       1776.000000   

       rating_denominator  
count         2356.000000  
mean            10.455433  
std              6.745237  
min              0.000000  
25%             10.000000  
50%             10.000000  
75%             10.000000  
max            170.000000

In [10]:
# Check quality issue on the name column
df_1['name'].value_counts()
# Remove "a", "an", "the" in df_1['name'] 
# Quality issue

None          745
a              55
Charlie        12
Cooper         11
Lucy           11
Oliver         11
Penny          10
Tucker         10
Lola           10
Winston         9
Bo              9
Sadie           8
the             8
Daisy           7
an              7
Bailey          7
Toby            7
Buddy           7
Dave            6
Koda            6
Jax             6
Oscar           6
Stanley         6
Jack            6
Rusty           6
Milo            6
Leo             6
Scout           6
Bella           6
Oakley          5
             ... 
Rambo           1
Superpup        1
Bloo            1
Farfle          1
Christoper      1
Jockson         1
Puff            1
Ralphé          1
Spanky          1
Godzilla        1
Trip            1
Ralf            1
Perry           1
Tug             1
Marlee          1
Alejandro       1
Bauer           1
Dale            1
Tedders         1
Tino            1
Eriq            1
Sprinkles       1
Clybe           1
Cal             1
Lolo      

In [11]:
list(df_1['name'])
# "his", "one" are not names
# Quality issue

['Phineas',
 'Tilly',
 'Archie',
 'Darla',
 'Franklin',
 'None',
 'Jax',
 'None',
 'Zoey',
 'Cassie',
 'Koda',
 'Bruno',
 'None',
 'Ted',
 'Stuart',
 'Oliver',
 'Jim',
 'Zeke',
 'Ralphus',
 'Canela',
 'Gerald',
 'Jeffrey',
 'such',
 'Canela',
 'None',
 'None',
 'Maya',
 'Mingus',
 'Derek',
 'Roscoe',
 'None',
 'Waffles',
 'None',
 'Jimbo',
 'Maisey',
 'None',
 'Lilly',
 'None',
 'Earl',
 'Lola',
 'Kevin',
 'None',
 'None',
 'Yogi',
 'Noah',
 'Bella',
 'Grizzwald',
 'None',
 'Rusty',
 'Gus',
 'Stanley',
 'Alfy',
 'Koko',
 'Rey',
 'Gary',
 'None',
 'a',
 'Elliot',
 'Louis',
 'None',
 'Bella',
 'Jesse',
 'None',
 'Romeo',
 'None',
 'Bailey',
 'Duddles',
 'Jack',
 'Emmy',
 'Steven',
 'Beau',
 'Snoopy',
 'None',
 'Shadow',
 'Terrance',
 'Shadow',
 'Emmy',
 'Aja',
 'None',
 'Penny',
 'Dante',
 'Nelly',
 'Ginger',
 'None',
 'Benedict',
 'Venti',
 'Goose',
 'Nugget',
 'None',
 'None',
 'Cash',
 'Coco',
 'Jed',
 'None',
 'Sebastian',
 'Walter',
 'None',
 'Sierra',
 'Sierra',
 'None',
 'None',
 

In [12]:
# Check to see if there is any quality issue in the doggo column
# doggo == "None" or "doggo"
df_1['doggo'].value_counts()
# No quality issue here

None     2259
doggo      97
Name: doggo, dtype: int64

In [13]:
# Check to see if there is any quality issue in the floofer column
# floofer == "None" or "floofer"
df_1['floofer'].value_counts()
# No quality issue here

None       2346
floofer      10
Name: floofer, dtype: int64

In [14]:
# Check to see if there is any quality issue in the pupper column
# pupper == "None" or "pupper"
df_1['pupper'].value_counts()
# No quality issue here

None      2099
pupper     257
Name: pupper, dtype: int64

In [15]:
# Check to see if there is any quality issue in the puppo column
# puppo == "None" or "puppo"
df_1['puppo'].value_counts()
# No quality issue here

None     2326
puppo      30
Name: puppo, dtype: int64

In [16]:
# Check to see if there is any quality issue in the rating_denominator column
# Rating_denominator == 10
df_1['rating_denominator'].value_counts()
# There are other values in this column rather than 10
# Quality issue

10     2333
11        3
50        3
80        2
20        2
2         1
16        1
40        1
70        1
15        1
90        1
110       1
120       1
130       1
150       1
170       1
7         1
0         1
Name: rating_denominator, dtype: int64

In [17]:
# Check if there is any duplicate tweet
sum(df_1['tweet_id'].duplicated())
# All clear

0

Assess df image

In [18]:
df_image.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075 entries, 0 to 2074
Data columns (total 12 columns):
tweet_id    2075 non-null int64
jpg_url     2075 non-null object
img_num     2075 non-null int64
p1          2075 non-null object
p1_conf     2075 non-null float64
p1_dog      2075 non-null bool
p2          2075 non-null object
p2_conf     2075 non-null float64
p2_dog      2075 non-null bool
p3          2075 non-null object
p3_conf     2075 non-null float64
p3_dog      2075 non-null bool
dtypes: bool(3), float64(3), int64(2), object(4)
memory usage: 152.1+ KB


In [19]:
df_image.describe()

tweet_id      img_num      p1_conf       p2_conf       p3_conf
count  2.075000e+03  2075.000000  2075.000000  2.075000e+03  2.075000e+03
mean   7.384514e+17     1.203855     0.594548  1.345886e-01  6.032417e-02
std    6.785203e+16     0.561875     0.271174  1.006657e-01  5.090593e-02
min    6.660209e+17     1.000000     0.044333  1.011300e-08  1.740170e-10
25%    6.764835e+17     1.000000     0.364412  5.388625e-02  1.622240e-02
50%    7.119988e+17     1.000000     0.588230  1.181810e-01  4.944380e-02
75%    7.932034e+17     1.000000     0.843855  1.955655e-01  9.180755e-02
max    8.924206e+17     4.000000     1.000000  4.880140e-01  2.734190e-01

In [20]:
# Check if there is any duplicate tweet
sum(df_image['tweet_id'].duplicated())
# All clear

0

In [21]:
# p1_conf <= 1
df_image['p1_conf'].max()
# No quality issue here

1.0

In [22]:
# p2_conf <= 1
df_image['p2_conf'].max()
# No quality issue here

0.48801400000000011

In [23]:
# p3_conf <= 1
df_image['p3_conf'].max()
# No quality issue here

0.27341900000000002

In [24]:
# p1_dog == "True" or "False"
df_image['p1_dog'].value_counts()
# No quality issue here

True     1532
False     543
Name: p1_dog, dtype: int64

In [25]:
# p2_dog == "True" or "False"
df_image['p2_dog'].value_counts()
# No quality issue here

True     1553
False     522
Name: p2_dog, dtype: int64

In [26]:
# p3_dog == "True" or "False"
df_image['p3_dog'].value_counts()
# No quality issue here

True     1499
False     576
Name: p3_dog, dtype: int64

Assess df_tweet

In [27]:
tweet_json.head()

contributors  coordinates          created_at display_text_range  \
0           NaN          NaN 2017-08-01 16:23:56            [0, 85]   
1           NaN          NaN 2017-08-01 00:17:27           [0, 138]   
2           NaN          NaN 2017-07-31 00:18:03           [0, 121]   
3           NaN          NaN 2017-07-30 15:58:51            [0, 79]   
4           NaN          NaN 2017-07-29 16:00:24           [0, 138]   

                                            entities  \
0  {'hashtags': [], 'symbols': [], 'user_mentions...   
1  {'hashtags': [], 'symbols': [], 'user_mentions...   
2  {'hashtags': [], 'symbols': [], 'user_mentions...   
3  {'hashtags': [], 'symbols': [], 'user_mentions...   
4  {'hashtags': [{'text': 'BarkWeek', 'indices': ...   

                                   extended_entities  favorite_count  \
0  {'media': [{'id': 892420639486877696, 'id_str'...           39467   
1  {'media': [{'id': 892177413194625024, 'id_str'...           33819   
2  {'media': [{'id': 891815175371796480, 'id_str'...           25461   
3  {'media': [{'id': 891689552724799489, 'id_str'...           42908   
4  {'media': [{'id': 891327551943041024, 'id_str'...           41048   

   favorited                                          full_text  geo  \
0      False  This is Phineas. He's a mystical boy. Only eve...  NaN   
1      False  This is Tilly. She's just checking pup on you....  NaN   
2      False  This is Archie. He is a rare Norwegian Pouncin...  NaN   
3      False  This is Darla. She commenced a snooze mid meal...  NaN   
4      False  This is Franklin. He would like you to stop ca...  NaN   

                         ...                          \
0                        ...                           
1                        ...                           
2                        ...                           
3                        ...                           
4                        ...                           

   possibly_sensitive_appealable  quoted_status quoted_status_id  \
0                            0.0            NaN              NaN   
1                            0.0            NaN              NaN   
2                            0.0            NaN              NaN   
3                            0.0            NaN              NaN   
4                            0.0            NaN              NaN   

   quoted_status_id_str  retweet_count  retweeted  retweeted_status  \
0                   NaN           8853      False               NaN   
1                   NaN           6514      False               NaN   
2                   NaN           4328      False               NaN   
3                   NaN           8964      False               NaN   
4                   NaN           9774      False               NaN   

                                              source truncated  \
0  <a href="http://twitter.com/download/iphone" r...     False   
1  <a href="http://twitter.com/download/iphone" r...     False   
2  <a href="http://twitter.com/download/iphone" r...     False   
3  <a href="http://twitter.com/download/iphone" r...     False   
4  <a href="http://twitter.com/download/iphone" r...     False   

                                                user  
0  {'id': 4196983835, 'id_str': '4196983835', 'na...  
1  {'id': 4196983835, 'id_str': '4196983835', 'na...  
2  {'id': 4196983835, 'id_str': '4196983835', 'na...  
3  {'id': 4196983835, 'id_str': '4196983835', 'na...  
4  {'id': 4196983835, 'id_str': '4196983835', 'na...  

[5 rows x 31 columns]

In [28]:
tweet_json.info()
# contributors does not have any data
# coordinates does not have any data
# geo does not have any data
# place has only one row
# favorite_count should be int
# id should be object


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2354 entries, 0 to 2353
Data columns (total 31 columns):
contributors                     0 non-null float64
coordinates                      0 non-null float64
created_at                       2354 non-null datetime64[ns]
display_text_range               2354 non-null object
entities                         2354 non-null object
extended_entities                2073 non-null object
favorite_count                   2354 non-null int64
favorited                        2354 non-null bool
full_text                        2354 non-null object
geo                              0 non-null float64
id                               2354 non-null int64
id_str                           2354 non-null int64
in_reply_to_screen_name          78 non-null object
in_reply_to_status_id            78 non-null float64
in_reply_to_status_id_str        78 non-null float64
in_reply_to_user_id              78 non-null float64
in_reply_to_user_id_str          78 n

In [29]:
tweet_json['quoted_status_id_str']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
5      NaN
6      NaN
7      NaN
8      NaN
9      NaN
10     NaN
11     NaN
12     NaN
13     NaN
14     NaN
15     NaN
16     NaN
17     NaN
18     NaN
19     NaN
20     NaN
21     NaN
22     NaN
23     NaN
24     NaN
25     NaN
26     NaN
27     NaN
28     NaN
29     NaN
        ..
2324   NaN
2325   NaN
2326   NaN
2327   NaN
2328   NaN
2329   NaN
2330   NaN
2331   NaN
2332   NaN
2333   NaN
2334   NaN
2335   NaN
2336   NaN
2337   NaN
2338   NaN
2339   NaN
2340   NaN
2341   NaN
2342   NaN
2343   NaN
2344   NaN
2345   NaN
2346   NaN
2347   NaN
2348   NaN
2349   NaN
2350   NaN
2351   NaN
2352   NaN
2353   NaN
Name: quoted_status_id_str, Length: 2354, dtype: float64

In [30]:
tweet_json['extended_entities'].sample(10)
# tidiness issue
# seperate tweet_json['extended_entities'] into columns by comma

2131    {'media': [{'id': 670073493971738624, 'id_str'...
2022    {'media': [{'id': 671891721769385984, 'id_str'...
1974    {'media': [{'id': 672995232229781504, 'id_str'...
1367                                                  NaN
2353    {'media': [{'id': 666020881337073664, 'id_str'...
1954    {'media': [{'id': 673612849076310016, 'id_str'...
2279    {'media': [{'id': 667369220322136065, 'id_str'...
309                                                   NaN
927     {'media': [{'id': 754481405627957248, 'id_str'...
1582    {'media': [{'id': 687096050230820864, 'id_str'...
Name: extended_entities, dtype: object

In [31]:
tweet_json['user'].sample(10)
# tidiness issue
# seperate tweet_json['user'] into columns by comma

119     {'id': 4196983835, 'id_str': '4196983835', 'na...
153     {'id': 4196983835, 'id_str': '4196983835', 'na...
1193    {'id': 4196983835, 'id_str': '4196983835', 'na...
1343    {'id': 4196983835, 'id_str': '4196983835', 'na...
2055    {'id': 4196983835, 'id_str': '4196983835', 'na...
89      {'id': 4196983835, 'id_str': '4196983835', 'na...
2301    {'id': 4196983835, 'id_str': '4196983835', 'na...
1278    {'id': 4196983835, 'id_str': '4196983835', 'na...
1458    {'id': 4196983835, 'id_str': '4196983835', 'na...
1770    {'id': 4196983835, 'id_str': '4196983835', 'na...
Name: user, dtype: object

In [32]:
tweet_json['quoted_status'].sample(10)
# tidiness issue
# value should not be a dictionary
# seperate values that contain a dictionary in tweet_json['quoted_status']

1099    NaN
1874    NaN
874     NaN
1153    NaN
1539    NaN
1602    NaN
1387    NaN
1073    NaN
647     NaN
1940    NaN
Name: quoted_status, dtype: object

In [33]:
tweet_json['retweeted_status'].sample(10)
# tidiness issue
# value should not be a dictionary
# seperate values that contain a dictionary in tweet_json['retweeted_status']

1077                                                  NaN
2330                                                  NaN
2343                                                  NaN
1359                                                  NaN
68                                                    NaN
1529                                                  NaN
584                                                   NaN
444                                                   NaN
301     {'created_at': 'Tue Feb 28 18:43:57 +0000 2017...
900                                                   NaN
Name: retweeted_status, dtype: object

In [34]:
tweet_json['source'].sample(10)
# quality issue
# Remove html tags in tweet_json['source']

156     <a href="http://twitter.com/download/iphone" r...
1603    <a href="http://twitter.com/download/iphone" r...
1544    <a href="http://twitter.com/download/iphone" r...
2099    <a href="http://twitter.com/download/iphone" r...
2147    <a href="http://twitter.com/download/iphone" r...
1188    <a href="http://twitter.com/download/iphone" r...
962     <a href="http://twitter.com/download/iphone" r...
2049    <a href="http://twitter.com/download/iphone" r...
1672    <a href="http://twitter.com/download/iphone" r...
110     <a href="http://twitter.com/download/iphone" r...
Name: source, dtype: object

In [35]:
tweet_json.describe()

contributors  coordinates  favorite_count  geo            id  \
count           0.0          0.0     2354.000000  0.0  2.354000e+03   
mean            NaN          NaN     8080.968564  NaN  7.426978e+17   
std             NaN          NaN    11814.771334  NaN  6.852812e+16   
min             NaN          NaN        0.000000  NaN  6.660209e+17   
25%             NaN          NaN     1415.000000  NaN  6.783975e+17   
50%             NaN          NaN     3603.500000  NaN  7.194596e+17   
75%             NaN          NaN    10122.250000  NaN  7.993058e+17   
max             NaN          NaN   132810.000000  NaN  8.924206e+17   

             id_str  in_reply_to_status_id  in_reply_to_status_id_str  \
count  2.354000e+03           7.800000e+01               7.800000e+01   
mean   7.426978e+17           7.455079e+17               7.455079e+17   
std    6.852812e+16           7.582492e+16               7.582492e+16   
min    6.660209e+17           6.658147e+17               6.658147e+17   
25%    6.783975e+17           6.757419e+17               6.757419e+17   
50%    7.194596e+17           7.038708e+17               7.038708e+17   
75%    7.993058e+17           8.257804e+17               8.257804e+17   
max    8.924206e+17           8.862664e+17               8.862664e+17   

       in_reply_to_user_id  in_reply_to_user_id_str  possibly_sensitive  \
count         7.800000e+01             7.800000e+01              2211.0   
mean          2.014171e+16             2.014171e+16                 0.0   
std           1.252797e+17             1.252797e+17                 0.0   
min           1.185634e+07             1.185634e+07                 0.0   
25%           3.086374e+08             3.086374e+08                 0.0   
50%           4.196984e+09             4.196984e+09                 0.0   
75%           4.196984e+09             4.196984e+09                 0.0   
max           8.405479e+17             8.405479e+17                 0.0   

       possibly_sensitive_appealable  quoted_status_id  quoted_status_id_str  \
count                         2211.0      2.900000e+01          2.900000e+01   
mean                             0.0      8.162686e+17          8.162686e+17   
std                              0.0      6.164161e+16          6.164161e+16   
min                              0.0      6.721083e+17          6.721083e+17   
25%                              0.0      7.888183e+17          7.888183e+17   
50%                              0.0      8.340867e+17          8.340867e+17   
75%                              0.0      8.664587e+17          8.664587e+17   
max                              0.0      8.860534e+17          8.860534e+17   

       retweet_count  
count    2354.000000  
mean     3164.797366  
std      5284.770364  
min         0.000000  
25%       624.500000  
50%      1473.500000  
75%      3652.000000  
max     79515.000000

# Quality issues

df_1

1) Change tweet id to object

2) Change retweeted_status_id to object

3) Change timestamp to date time

4) Change retweeted_status_timestamp to date time

5) Remove "a", "an", "the", "his", "her", "one" in df_1['name'] 

6) Change all rows whose values != 10 in df_1['rating_denominator'] to 10

tweet_json

7) Drop columns that do not contain values: contributors, coordinates, geo, place, possibly_sensitive, possibly_sensitive_id, possibly_sensitive_id_string

8) favorite_count should be int

9) id should be object

df_image

8) Remove values that are not dog breeds in p1, p2 and p3

# Tidiness issues

df_1

12) Remove html command <href> in the expanded_urls

tweet_json.txt

13) Remove html tags in tweet_json['source']

# Clean

df_1

In [36]:
# 1) Change tweet id to object
df_1['tweet_id'] = df_1['tweet_id'].astype(object)

In [37]:
# 2) Change retweeted_status_id to object
df_1['retweeted_status_id'] = df_1['retweeted_status_id'].astype(object)

In [38]:
# 3) Change timestamp to date time
df_1['timestamp'] = df_1['timestamp'].astype('datetime64[ns]')

In [39]:
# 4) Change retweeted_status_timestamp to date time
df_1['retweeted_status_timestamp'] = df_1['retweeted_status_timestamp'].astype('datetime64[ns]')

In [40]:
# 6) Remove "a", "an", "the", "his", "her", "one" in df_1['name']
df_1['name'] = df_1['name'].replace(['a','an','the','his','her','one','not'],'None')
list(df_1['name'])

['Phineas',
 'Tilly',
 'Archie',
 'Darla',
 'Franklin',
 'None',
 'Jax',
 'None',
 'Zoey',
 'Cassie',
 'Koda',
 'Bruno',
 'None',
 'Ted',
 'Stuart',
 'Oliver',
 'Jim',
 'Zeke',
 'Ralphus',
 'Canela',
 'Gerald',
 'Jeffrey',
 'such',
 'Canela',
 'None',
 'None',
 'Maya',
 'Mingus',
 'Derek',
 'Roscoe',
 'None',
 'Waffles',
 'None',
 'Jimbo',
 'Maisey',
 'None',
 'Lilly',
 'None',
 'Earl',
 'Lola',
 'Kevin',
 'None',
 'None',
 'Yogi',
 'Noah',
 'Bella',
 'Grizzwald',
 'None',
 'Rusty',
 'Gus',
 'Stanley',
 'Alfy',
 'Koko',
 'Rey',
 'Gary',
 'None',
 'None',
 'Elliot',
 'Louis',
 'None',
 'Bella',
 'Jesse',
 'None',
 'Romeo',
 'None',
 'Bailey',
 'Duddles',
 'Jack',
 'Emmy',
 'Steven',
 'Beau',
 'Snoopy',
 'None',
 'Shadow',
 'Terrance',
 'Shadow',
 'Emmy',
 'Aja',
 'None',
 'Penny',
 'Dante',
 'Nelly',
 'Ginger',
 'None',
 'Benedict',
 'Venti',
 'Goose',
 'Nugget',
 'None',
 'None',
 'Cash',
 'Coco',
 'Jed',
 'None',
 'Sebastian',
 'Walter',
 'None',
 'Sierra',
 'Sierra',
 'None',
 'None'

In [41]:
# 7) Change all rows whose values != 10 in df_1['rating_denominator'] to 10
df_1['rating_denominator'] = df_1['rating_denominator'].replace([11,50,80,20,2,16,40,70,15,90,110,120,130,150,170,7,0],10)
df_1['rating_denominator'].value_counts()

10    2356
Name: rating_denominator, dtype: int64

In [42]:
# 12) Remove html command in the expanded_urls
df_1['source'] = df_1['source'].str.strip("<a href=")
df_1['source'] = df_1['source'].str.strip("</a>")
df_1['source'] = df_1['source'].str.split(pat="rel=", expand=True)
df_1['source'].sample(5)

427    "http://twitter.com/download/iphone" 
429    "http://twitter.com/download/iphone" 
184    "http://twitter.com/download/iphone" 
106    "http://twitter.com/download/iphone" 
575    "http://twitter.com/download/iphone" 
Name: source, dtype: object

In [43]:
df_1

tweet_id  in_reply_to_status_id  in_reply_to_user_id  \
0     892420643555336193                    NaN                  NaN   
1     892177421306343426                    NaN                  NaN   
2     891815181378084864                    NaN                  NaN   
3     891689557279858688                    NaN                  NaN   
4     891327558926688256                    NaN                  NaN   
5     891087950875897856                    NaN                  NaN   
6     890971913173991426                    NaN                  NaN   
7     890729181411237888                    NaN                  NaN   
8     890609185150312448                    NaN                  NaN   
9     890240255349198849                    NaN                  NaN   
10    890006608113172480                    NaN                  NaN   
11    889880896479866881                    NaN                  NaN   
12    889665388333682689                    NaN                  NaN   
13    889638837579907072                    NaN                  NaN   
14    889531135344209921                    NaN                  NaN   
15    889278841981685760                    NaN                  NaN   
16    888917238123831296                    NaN                  NaN   
17    888804989199671297                    NaN                  NaN   
18    888554962724278272                    NaN                  NaN   
19    888202515573088257                    NaN                  NaN   
20    888078434458587136                    NaN                  NaN   
21    887705289381826560                    NaN                  NaN   
22    887517139158093824                    NaN                  NaN   
23    887473957103951883                    NaN                  NaN   
24    887343217045368832                    NaN                  NaN   
25    887101392804085760                    NaN                  NaN   
26    886983233522544640                    NaN                  NaN   
27    886736880519319552                    NaN                  NaN   
28    886680336477933568                    NaN                  NaN   
29    886366144734445568                    NaN                  NaN   
...                  ...                    ...                  ...   
2326  666411507551481857                    NaN                  NaN   
2327  666407126856765440                    NaN                  NaN   
2328  666396247373291520                    NaN                  NaN   
2329  666373753744588802                    NaN                  NaN   
2330  666362758909284353                    NaN                  NaN   
2331  666353288456101888                    NaN                  NaN   
2332  666345417576210432                    NaN                  NaN   
2333  666337882303524864                    NaN                  NaN   
2334  666293911632134144                    NaN                  NaN   
2335  666287406224695296                    NaN                  NaN   
2336  666273097616637952                    NaN                  NaN   
2337  666268910803644416                    NaN                  NaN   
2338  666104133288665088                    NaN                  NaN   
2339  666102155909144576                    NaN                  NaN   
2340  666099513787052032                    NaN                  NaN   
2341  666094000022159362                    NaN                  NaN   
2342  666082916733198337                    NaN                  NaN   
2343  666073100786774016                    NaN                  NaN   
2344  666071193221509120                    NaN                  NaN   
2345  666063827256086533                    NaN                  NaN   
2346  666058600524156928                    NaN                  NaN   
2347  666057090499244032                    NaN                  NaN   
2348  666055525042405380                    NaN                  NaN   
2349  666051853826850816                    NaN         

tweet_json

In [44]:
# 9) Remove html tags in tweet_json['source']
tweet_json['source'] = tweet_json['source'].str.strip("<a href=")
tweet_json['source'] = tweet_json['source'].str.strip("</a>")
tweet_json['source'] = tweet_json['source'].str.split(pat="rel=", expand=True)
tweet_json['source'].sample(5)

1248    "http://twitter.com/download/iphone" 
232     "http://twitter.com/download/iphone" 
798     "http://twitter.com/download/iphone" 
284     "http://twitter.com/download/iphone" 
2019    "http://twitter.com/download/iphone" 
Name: source, dtype: object

In [45]:
# 10) Drop columns that do not contain values: contributors, coordinates, geo, place, possibly_sensitive, possibly_sensitive_appealable,lang, entities, extend_entities
tweet_json = tweet_json.drop(columns=['contributors','coordinates','geo','place','possibly_sensitive','lang','possibly_sensitive_appealable', 'id_str','retweeted_status','in_reply_to_user_id_str','quoted_status_id_str','entities','extended_entities', 'in_reply_to_screen_name', 'in_reply_to_status_id', 'in_reply_to_status_id_str','in_reply_to_user_id','quoted_status','quoted_status_id','user'])
tweet_json.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2354 entries, 0 to 2353
Data columns (total 11 columns):
created_at            2354 non-null datetime64[ns]
display_text_range    2354 non-null object
favorite_count        2354 non-null int64
favorited             2354 non-null bool
full_text             2354 non-null object
id                    2354 non-null int64
is_quote_status       2354 non-null bool
retweet_count         2354 non-null int64
retweeted             2354 non-null bool
source                2354 non-null object
truncated             2354 non-null bool
dtypes: bool(4), datetime64[ns](1), int64(3), object(3)
memory usage: 138.0+ KB


In [46]:
tweet_json.head()

created_at display_text_range  favorite_count  favorited  \
0 2017-08-01 16:23:56            [0, 85]           39467      False   
1 2017-08-01 00:17:27           [0, 138]           33819      False   
2 2017-07-31 00:18:03           [0, 121]           25461      False   
3 2017-07-30 15:58:51            [0, 79]           42908      False   
4 2017-07-29 16:00:24           [0, 138]           41048      False   

                                           full_text                  id  \
0  This is Phineas. He's a mystical boy. Only eve...  892420643555336193   
1  This is Tilly. She's just checking pup on you....  892177421306343426   
2  This is Archie. He is a rare Norwegian Pouncin...  891815181378084864   
3  This is Darla. She commenced a snooze mid meal...  891689557279858688   
4  This is Franklin. He would like you to stop ca...  891327558926688256   

   is_quote_status  retweet_count  retweeted  \
0            False           8853      False   
1            False           6514      False   
2            False           4328      False   
3            False           8964      False   
4            False           9774      False   

                                  source  truncated  
0  "http://twitter.com/download/iphone"       False  
1  "http://twitter.com/download/iphone"       False  
2  "http://twitter.com/download/iphone"       False  
3  "http://twitter.com/download/iphone"       False  
4  "http://twitter.com/download/iphone"       False

In [47]:
tweet_json = tweet_json.rename(columns={'id': 'tweet_id', 'full_text': 'text', 'created_at': 'timestamp'})

In [48]:
# change the tweet_id data type from int64 to object
tweet_json['tweet_id'] = tweet_json['tweet_id'].astype(object)

In [49]:
tweet_json.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2354 entries, 0 to 2353
Data columns (total 11 columns):
timestamp             2354 non-null datetime64[ns]
display_text_range    2354 non-null object
favorite_count        2354 non-null int64
favorited             2354 non-null bool
text                  2354 non-null object
tweet_id              2354 non-null object
is_quote_status       2354 non-null bool
retweet_count         2354 non-null int64
retweeted             2354 non-null bool
source                2354 non-null object
truncated             2354 non-null bool
dtypes: bool(4), datetime64[ns](1), int64(2), object(4)
memory usage: 138.0+ KB


In [50]:
df_1 = df_1.drop(columns=['in_reply_to_status_id', 'in_reply_to_user_id', 'retweeted_status_id', 'retweeted_status_user_id', 'retweeted_status_timestamp'])

In [51]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 12 columns):
tweet_id              2356 non-null object
timestamp             2356 non-null datetime64[ns]
source                2356 non-null object
text                  2356 non-null object
expanded_urls         2297 non-null object
rating_numerator      2356 non-null int64
rating_denominator    2356 non-null int64
name                  2356 non-null object
doggo                 2356 non-null object
floofer               2356 non-null object
pupper                2356 non-null object
puppo                 2356 non-null object
dtypes: datetime64[ns](1), int64(2), object(9)
memory usage: 221.0+ KB


In [52]:
df_clean = df_1.merge(tweet_json, how='outer', on=['tweet_id','text', 'timestamp', 'source'])

In [53]:
df_clean.head()

tweet_id           timestamp  \
0  892420643555336193 2017-08-01 16:23:56   
1  892177421306343426 2017-08-01 00:17:27   
2  891815181378084864 2017-07-31 00:18:03   
3  891689557279858688 2017-07-30 15:58:51   
4  891327558926688256 2017-07-29 16:00:24   

                                  source  \
0  "http://twitter.com/download/iphone"    
1  "http://twitter.com/download/iphone"    
2  "http://twitter.com/download/iphone"    
3  "http://twitter.com/download/iphone"    
4  "http://twitter.com/download/iphone"    

                                                text  \
0  This is Phineas. He's a mystical boy. Only eve...   
1  This is Tilly. She's just checking pup on you....   
2  This is Archie. He is a rare Norwegian Pouncin...   
3  This is Darla. She commenced a snooze mid meal...   
4  This is Franklin. He would like you to stop ca...   

                                       expanded_urls  rating_numerator  \
0  https://twitter.com/dog_rates/status/892420643...                13   
1  https://twitter.com/dog_rates/status/892177421...                13   
2  https://twitter.com/dog_rates/status/891815181...                12   
3  https://twitter.com/dog_rates/status/891689557...                13   
4  https://twitter.com/dog_rates/status/891327558...                12   

   rating_denominator      name doggo floofer pupper puppo display_text_range  \
0                  10   Phineas  None    None   None  None            [0, 85]   
1                  10     Tilly  None    None   None  None           [0, 138]   
2                  10    Archie  None    None   None  None           [0, 121]   
3                  10     Darla  None    None   None  None            [0, 79]   
4                  10  Franklin  None    None   None  None           [0, 138]   

   favorite_count favorited is_quote_status  retweet_count retweeted truncated  
0         39467.0     False           False         8853.0     False     False  
1         33819.0     False           False         6514.0     False     False  
2         25461.0     False           False         4328.0     False     False  
3         42908.0     False           False         8964.0     False     False  
4         41048.0     False           False         9774.0     False     False

In [54]:
df_image.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075 entries, 0 to 2074
Data columns (total 12 columns):
tweet_id    2075 non-null int64
jpg_url     2075 non-null object
img_num     2075 non-null int64
p1          2075 non-null object
p1_conf     2075 non-null float64
p1_dog      2075 non-null bool
p2          2075 non-null object
p2_conf     2075 non-null float64
p2_dog      2075 non-null bool
p3          2075 non-null object
p3_conf     2075 non-null float64
p3_dog      2075 non-null bool
dtypes: bool(3), float64(3), int64(2), object(4)
memory usage: 152.1+ KB


In [55]:
# change the tweet_id data type from int64 to object
df_image['tweet_id'] = df_image['tweet_id'].astype(object)

In [56]:
df_clean = df_clean.merge(df_image, how='outer', on=['tweet_id'])

In [57]:
df_clean.head()

tweet_id           timestamp  \
0  892420643555336193 2017-08-01 16:23:56   
1  892177421306343426 2017-08-01 00:17:27   
2  891815181378084864 2017-07-31 00:18:03   
3  891689557279858688 2017-07-30 15:58:51   
4  891327558926688256 2017-07-29 16:00:24   

                                  source  \
0  "http://twitter.com/download/iphone"    
1  "http://twitter.com/download/iphone"    
2  "http://twitter.com/download/iphone"    
3  "http://twitter.com/download/iphone"    
4  "http://twitter.com/download/iphone"    

                                                text  \
0  This is Phineas. He's a mystical boy. Only eve...   
1  This is Tilly. She's just checking pup on you....   
2  This is Archie. He is a rare Norwegian Pouncin...   
3  This is Darla. She commenced a snooze mid meal...   
4  This is Franklin. He would like you to stop ca...   

                                       expanded_urls  rating_numerator  \
0  https://twitter.com/dog_rates/status/892420643...                13   
1  https://twitter.com/dog_rates/status/892177421...                13   
2  https://twitter.com/dog_rates/status/891815181...                12   
3  https://twitter.com/dog_rates/status/891689557...                13   
4  https://twitter.com/dog_rates/status/891327558...                12   

   rating_denominator      name doggo floofer  ...   img_num           p1  \
0                  10   Phineas  None    None  ...       1.0       orange   
1                  10     Tilly  None    None  ...       1.0    Chihuahua   
2                  10    Archie  None    None  ...       1.0    Chihuahua   
3                  10     Darla  None    None  ...       1.0  paper_towel   
4                  10  Franklin  None    None  ...       2.0       basset   

    p1_conf  p1_dog                  p2   p2_conf  p2_dog  \
0  0.097049   False               bagel  0.085851   False   
1  0.323581    True            Pekinese  0.090647    True   
2  0.716012    True            malamute  0.078253    True   
3  0.170278   False  Labrador_retriever  0.168086    True   
4  0.555712    True    English_springer  0.225770    True   

                            p3   p3_conf p3_dog  
0                       banana  0.076110  False  
1                     papillon  0.068957   True  
2                       kelpie  0.031379   True  
3                      spatula  0.040836  False  
4  German_short-haired_pointer  0.175219   True  

[5 rows x 30 columns]

In [58]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2356 entries, 0 to 2355
Data columns (total 30 columns):
tweet_id              2356 non-null object
timestamp             2356 non-null datetime64[ns]
source                2356 non-null object
text                  2356 non-null object
expanded_urls         2297 non-null object
rating_numerator      2356 non-null int64
rating_denominator    2356 non-null int64
name                  2356 non-null object
doggo                 2356 non-null object
floofer               2356 non-null object
pupper                2356 non-null object
puppo                 2356 non-null object
display_text_range    2354 non-null object
favorite_count        2354 non-null float64
favorited             2354 non-null object
is_quote_status       2354 non-null object
retweet_count         2354 non-null float64
retweeted             2354 non-null object
truncated             2354 non-null object
jpg_url               2075 non-null object
img_num               207

# Visualization

Question 1: Is there a correlation between nickname and number of favorites or retweets?

In [59]:
# create a new dataframe that has only the tweet_id, favorite_count, retweet_count and nicknames. Create a column for tweets that don't contain any dog nickname
df_nickname = pd.DataFrame(df_clean, columns = ['tweet_id', 'favorite_count', 'retweet_count', 'doggo', 'floofer', 'pupper', 'puppo'])

In [60]:
# I change values that contain the nick name to 1 and the ones that don't contain any value to 0 for quick data view
df_nickname['doggo'] = df_nickname['doggo'].replace(['doggo','None'],['1','0'])
df_nickname['floofer'] = df_nickname['floofer'].replace(['floofer','None'],['1','0'])
df_nickname['pupper'] = df_nickname['pupper'].replace(['pupper','None'],['1','0'])
df_nickname['puppo'] = df_nickname['puppo'].replace(['puppo','None'],['1','0'])
df_nickname['doggo'].astype(int)
df_nickname['floofer'].astype(int)
df_nickname['puppo'].astype(int)
df_nickname['pupper'].astype(int)

0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      1
       ..
2326    0
2327    0
2328    0
2329    0
2330    0
2331    0
2332    0
2333    0
2334    0
2335    0
2336    0
2337    0
2338    0
2339    0
2340    0
2341    0
2342    0
2343    0
2344    0
2345    0
2346    0
2347    0
2348    0
2349    0
2350    0
2351    0
2352    0
2353    0
2354    0
2355    0
Name: pupper, Length: 2356, dtype: int64

In [61]:
df_nickname.loc[(df_nickname['doggo'] == '0') & (df_nickname['floofer'] == '0') & (df_nickname['pupper'] == '0') & (df_nickname['puppo'] == '0'), 'no_nickname'] = 1
df_nickname.loc[(df_nickname['doggo'] == '1') | (df_nickname['floofer'] == '1') | (df_nickname['pupper'] == '1') | (df_nickname['puppo'] == '1'), 'no_nickname'] = 0

In [62]:
df_nickname['no_nickname'] = df_nickname['no_nickname'].astype(object)

In [63]:
df_nickname.sample(10)

tweet_id  favorite_count  retweet_count doggo floofer pupper  \
1     892177421306343426         33819.0         6514.0     0       0      0   
1161  723912936180330496          4236.0         1374.0     0       0      0   
1969  673317986296586240           924.0          293.0     0       0      0   
1817  676603393314578432          1280.0          440.0     0       0      1   
2134  670069087419133954           676.0          278.0     0       0      0   
2231  668226093875376128           323.0          115.0     0       0      0   
444   819238181065359361          2550.0          462.0     0       0      1   
911   757597904299253760             0.0          336.0     0       0      1   
2247  667873844930215936           667.0          440.0     0       0      0   
273   840728873075638272             0.0        18285.0     0       0      0   

     puppo no_nickname  
1        0           1  
1161     0           1  
1969     0           1  
1817     0           0  
2134     0           1  
2231     0           1  
444      0           0  
911      0           0  
2247     0           1  
273      0           1

In [64]:
df_nickname.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2356 entries, 0 to 2355
Data columns (total 8 columns):
tweet_id          2356 non-null object
favorite_count    2354 non-null float64
retweet_count     2354 non-null float64
doggo             2356 non-null object
floofer           2356 non-null object
pupper            2356 non-null object
puppo             2356 non-null object
no_nickname       2356 non-null object
dtypes: float64(2), object(6)
memory usage: 165.7+ KB


In [65]:
# Only keep rows that contain the nickname
doggo = df_nickname.drop(columns = ['tweet_id', 'floofer', 'pupper', 'puppo', 'no_nickname'])
doggo = doggo[doggo.doggo != '0']
doggo.describe()

favorite_count  retweet_count
count       97.000000      97.000000
mean     15345.010309    7295.494845
std      19785.868648   12378.265124
min          0.000000      39.000000
25%       5272.000000    2042.000000
50%      10042.000000    3327.000000
75%      16304.000000    5757.000000
max     131075.000000   79515.000000

In [66]:
# Only keep rows that contain the nickname
floofer = df_nickname.drop(columns = ['tweet_id', 'doggo', 'pupper', 'puppo', 'no_nickname'])
floofer = floofer[floofer.floofer != '0']
floofer.describe()

favorite_count  retweet_count
count        10.00000      10.000000
mean      11674.90000    4083.600000
std       10253.00493    5275.497664
min        1618.00000     496.000000
25%        4391.25000    1381.750000
50%        8689.00000    2887.000000
75%       15990.75000    3727.000000
max       33345.00000   18497.000000

In [67]:
# Only keep rows that contain the nickname
pupper = df_nickname.drop(columns = ['tweet_id', 'floofer', 'doggo', 'puppo', 'no_nickname'])
pupper = pupper[pupper.pupper != '0']
pupper.describe()

favorite_count  retweet_count
count      256.000000     256.000000
mean      6750.996094    2982.199219
std      10321.533383    4592.451363
min          0.000000      26.000000
25%       2123.750000     737.500000
50%       3194.000000    1375.000000
75%       7474.250000    3264.000000
max     106827.000000   32883.000000

In [68]:
# Only keep rows that contain the nickname
puppo = df_nickname.drop(columns = ['tweet_id', 'floofer', 'pupper', 'doggo', 'no_nickname'])
puppo = puppo[puppo.puppo != '0']
puppo.describe()

favorite_count  retweet_count
count       30.000000      30.000000
mean     18225.900000    6581.133333
std      25987.198406    9290.067361
min          0.000000     179.000000
25%       4861.750000    1538.250000
50%      10667.500000    3230.000000
75%      19691.250000    8536.000000
max     132810.000000   48265.000000

In [69]:
# Only keep rows that does not contain a nickname
no_nickname = df_nickname.drop(columns = ['tweet_id', 'floofer', 'pupper', 'puppo', 'doggo'])
no_nickname = no_nickname[no_nickname.no_nickname != 0]
no_nickname.describe()

favorite_count  retweet_count
count     1975.000000    1975.000000
mean      7761.082025    2948.880506
std      10965.312058    4582.093147
min          0.000000       0.000000
25%       1266.500000     581.000000
50%       3504.000000    1374.000000
75%       9734.000000    3538.000000
max     107956.000000   56625.000000

In [70]:
# create a new dataframe with favorite_mean and retweet_mean
fav_retweet = pd.DataFrame(data=[['15345', '7295'], ['11674', '4083'], ['6750', '2982'], ['18225', '6581'], ['7761', '2948']],
                                    columns= ['favorite_mean', 'retweet_mean'],
                                    index=['Doggo', 'Floofer', 'Pupper', 'Puppo', 'No_nickname'] )

In [71]:
fav_retweet.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Doggo to No_nickname
Data columns (total 2 columns):
favorite_mean    5 non-null object
retweet_mean     5 non-null object
dtypes: object(2)
memory usage: 120.0+ bytes


In [72]:
fav_retweet['favorite_mean'] = fav_retweet['favorite_mean'].astype(int)
fav_retweet['retweet_mean'] = fav_retweet['retweet_mean'].astype(int)

In [73]:
fav_retweet

favorite_mean  retweet_mean
Doggo                15345          7295
Floofer              11674          4083
Pupper                6750          2982
Puppo                18225          6581
No_nickname           7761          2948

In [74]:
fav_retweet.plot.bar(title='Average favorite and retweet counts by dog nicknames', stacked=True)

Tweets contain dog nicknames "puppo" ranked the highest average favorite count with 18225.
In contrast, tweets with dog nickanme "pupper" in them receivw the lowest favorite count with only 6750 on average.
So go for "puppo" not "pupper".

Tweets contain dog nicknames "doggo" that has the highest average retwwet count with 7295.
On contraty, tweets with no dog nicknames at all ranked lowest retweet count at 2948.
So use a dog slang for more retweet.

Question 2: What are the top 10 most popular dog breed get recognized by image scanner and their average confidence interval?

In [83]:
df_breed = pd.DataFrame(df_clean, columns = ['tweet_id', 'p1','p1_conf','p1_dog','p2','p2_conf','p2_dog', 'p3','p3_conf','p3_dog', 'dog_breed'])

In [84]:
df_breed.head(10)

tweet_id                        p1   p1_conf p1_dog  \
0  892420643555336193                    orange  0.097049  False   
1  892177421306343426                 Chihuahua  0.323581   True   
2  891815181378084864                 Chihuahua  0.716012   True   
3  891689557279858688               paper_towel  0.170278  False   
4  891327558926688256                    basset  0.555712   True   
5  891087950875897856  Chesapeake_Bay_retriever  0.425595   True   
6  890971913173991426               Appenzeller  0.341703   True   
7  890729181411237888                Pomeranian  0.566142   True   
8  890609185150312448             Irish_terrier  0.487574   True   
9  890240255349198849                  Pembroke  0.511319   True   

                   p2   p2_conf p2_dog                           p3   p3_conf  \
0               bagel  0.085851  False                       banana  0.076110   
1            Pekinese  0.090647   True                     papillon  0.068957   
2            malamute  0.078253   True                       kelpie  0.031379   
3  Labrador_retriever  0.168086   True                      spatula  0.040836   
4    English_springer  0.225770   True  German_short-haired_pointer  0.175219   
5       Irish_terrier  0.116317   True              Indian_elephant  0.076902   
6       Border_collie  0.199287   True                    ice_lolly  0.193548   
7          Eskimo_dog  0.178406   True                     Pembroke  0.076507   
8        Irish_setter  0.193054   True     Chesapeake_Bay_retriever  0.118184   
9            Cardigan  0.451038   True                    Chihuahua  0.029248   

  p3_dog  dog_breed  
0  False        NaN  
1   True        NaN  
2   True        NaN  
3  False        NaN  
4   True        NaN  
5  False        NaN  
6  False        NaN  
7   True        NaN  
8   True        NaN  
9   True        NaN

In [85]:
df_breed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2356 entries, 0 to 2355
Data columns (total 11 columns):
tweet_id     2356 non-null object
p1           2075 non-null object
p1_conf      2075 non-null float64
p1_dog       2075 non-null object
p2           2075 non-null object
p2_conf      2075 non-null float64
p2_dog       2075 non-null object
p3           2075 non-null object
p3_conf      2075 non-null float64
p3_dog       2075 non-null object
dog_breed    0 non-null float64
dtypes: float64(4), object(7)
memory usage: 220.9+ KB


In [86]:
df_breed['dog_breed'] = []

for p1, p2, p3, p1_dog, p2_dog, p3_dog, p1_conf, p2_conf, p3_conf in df_breed:
    if(p1_dog=='False' & p2_dog=='False' & p3_dog=='False'):
        dog_breed = Null

    # scenario 2: one True case
    elif(p1_dog=='True' & p2_dog=='False' & p3_dog =='False'):
        dog_breed = p1     
    elif(p1_dog=='False' & p2_dog=='True' & p3_dog =='False'):
        dog_breed = p2     
    elif(p1_dog=='True' & p2_dog=='False' & p3_dog =='True'):
        dog_breed = p3

    # scenario 3: two True cases    
    # p1_dog and p2_dog == 'True'
    elif(p1_dog=='True' & p2_dog=='True' & p3_dog=='False' & p1_conf >= p2_conf):
        dog_breed = p1    
    elif(p1_dog=='True' & p2_dog=='True' & p3_dog=='False' & p1_conf < p2_conf):
        dog_breed = p2

    # p1_dog and p3_dog == 'True'
    elif(p1_dog=='True' & p3_dog=='True' & p2_dog=='False' & p1_conf >= p3_conf):
        dog_breed = p1      
    elif (p1_dog=='True' & p3_dog=='True' & p2_dog=='False' & p1_conf < p3_conf):
        dog_breed = p3

    # p2_dog and p3_dog == 'True'
    elif(p2_dog=='True' & p3_dog=='True' & p1_dog=='False' & p2_conf >= p3_conf):
        dog_breed = p2      
    elif(p2_dog=='True' & p3_dog=='True' & p1_dog=='False' & p2_conf < p3_conf):
        dog_breed = p3        


    # scenario 4: all cases are True
    # p1 >= p2 & p3
    elif(p1_dog=='True' & p2_dog=='True' & p3_dog=='True' & p1 >= p2 & p1 >= p3):
        dog_breed = p1
    #p2 > p1 & p2 >= P3
    elif(p1_dog=='True' & p2_dog=='True' & p3_dog=='True' & p2 > p1 & p2 >= p3):
        dog_breed = p2

    # p3 > p1 & p2
    else:
        dog_breed = p3

ValueError: Length of values does not match length of index